In [64]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [65]:
df = pd.read_csv(r"C:\Users\cashk\OneDrive\Desktop\Projects\Customer Churn ML\Churn_predictor_ML\data\telco_comm_churn.csv")
pd.set_option('display.max_columns', None)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [66]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [67]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

### Hanlding missing values

In [68]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [69]:
df.fillna({'TotalCharges': df['TotalCharges'].median()}, inplace=True)

In [70]:
df.isnull().sum().sum()

0

### Feature Engineering

##### Creating New Features

In [71]:
df['tenure'].min(), df['tenure'].max()

(0, 72)

In [72]:
df['tenure_group']= pd.cut(df['tenure'], bins=5, labels=['0', '1', '2', '3', '4'], include_lowest=True)
df['tenure_group']

0       0
1       2
2       0
3       3
4       0
5       0
6       1
7       0
8       1
9       4
10      0
11      1
12      4
13      3
14      1
15      4
16      3
17      4
18      0
19      1
20      0
21      0
22      0
23      4
24      3
25      2
26      3
27      0
28      4
29      1
30      4
31      0
32      1
33      0
34      0
35      4
36      0
37      3
38      2
39      0
40      0
41      4
42      1
43      4
44      0
45      3
46      0
47      0
48      3
49      4
50      2
51      1
52      1
53      0
54      4
55      1
56      4
57      4
58      2
59      4
60      3
61      4
62      4
63      1
64      0
65      0
66      3
67      2
68      3
69      0
70      0
71      3
72      4
73      4
74      0
75      3
76      3
77      0
78      2
79      3
80      0
81      0
82      0
83      2
84      3
85      0
86      2
87      3
88      3
89      2
90      2
91      0
92      4
93      4
94      4
95      0
96      4
97      0
98      3
99      1
100     0
101     0
102     2
103     4
104     4
105     0
106     4
107     2
108     2
109     4
110     3
111     3
112     2
113     2
114     4
115     0
116     2
117     0
118     2
119     1
120     3
121     0
122     0
123     0
124     0
125     2
126     1
127     4
128     0
129     4
130     0
131     1
132     4
133     0
134     0
135     2
136     1
137     4
138     3
139     0
140     4
141     0
142     4
143     4
144     4
145     4
146     0
147     0
148     2
149     1
150     0
151     0
152     4
153     4
154     0
155     0
156     1
157     1
158     1
159     0
160     0
161     1
162     0
163     3
164     0
165     4
166     0
167     4
168     4
169     1
170     2
171     0
172     0
173     3
174     2
175     2
176     1
177     0
178     1
179     4
180     0
181     0
182     0
183     2
184     0
185     0
186     1
187     0
188     0
189     2
190     2
191     0
192     4
193     4
194     4
195     1
196     1
197     4
198     4
199     0
200     1
201     0
202     4
203     0
204     3
205     2
206     4
207     0
208     1
209     4
210     0
211     0
212     4
213     2
214     1
215     3
216     4
217     4
218     4
219     0
220     0
221     4
222     0
223     0
224     0
225     1
226     2
227     0
228     2
229     3
230     3
231     3
232     0
233     4
234     2
235     0
236     0
237     1
238     0
239     1
240     4
241     4
242     2
243     4
244     0
245     0
246     2
247     1
248     0
249     2
250     3
251     0
252     0
253     2
254     0
255     4
256     4
257     3
258     0
259     2
260     0
261     0
262     3
263     2
264     3
265     4
266     3
267     1
268     4
269     4
270     1
271     3
272     0
273     1
274     0
275     0
276     3
277     1
278     0
279     0
280     0
281     0
282     0
283     4
284     1
285     1
286     1
287     0
288     0
289     0
290     1
291     2
292     1
293     0
294     0
295     0
296     4
297     2
298     2
299     0
300     1
301     0
302     0
303     4
304     2
305     3
306     2
307     2
308     2
309     3
310     0
311     1
312     2
313     0
314     0
315     3
316     4
317     2
318     1
319     2
320     3
321     4
322     0
323     0
324     4
325     3
326     0
327     0
328     1
329     1
330     2
331     0
332     3
333     0
334     0
335     4
336     2
337     4
338     2
339     4
340     2
341     4
342     4
343     4
344     2
345     0
346     0
347     4
348     1
349     4
350     2
351     1
352     0
353     0
354     1
355     0
356     1
357     4
358     1
359     2
360     0
361     2
362     4
363     3
364     1
365     0
366     1
367     0
368     4
369     4
370     2
371     0
372     1
373     3
374     2
375     2
376     0
377     1
378     4
379     1
380     2
381     0
382     4
383     0
384     3
385     0
386     3
387     2
388     3
389     0
390     1
391     1
392     0
393     1
394     2
395     4
396     2
397     2
398     2
399     1
400     2
401     0
402     4
403     4
404     1
405     4
406     4
407     2
408     0
409     0
410     0
411     3
412     2
413     3
414     3
415     1
416     4
417     2
418     1
419     0
420     0
421     0
422     2
423     3
424     0
425     3
426     3
427     0
428     1
429     4
430     4
431     4
432     0
433     0
434     2
435     1
436     2
437     4
438     2
439     0
440     1
441     3
442     3
443     1
444     2
445     4
446     0
447     3
448     0
449     4
450     4
451     1
452     4
453     1
454     4
455     1
456     1
457     2
458     0
459     0
460     0
461     1
462     0
463     0
464     4
465     4
466     4
467     4
468     3
469     0
470     1
471     0
472     0
473     1
474     0
475     1
476     2
477     0
478     0
479     1
480     0
481     3
482     1
483     4
484     0
485     4
486     1
487     4
488     0
489     0
490     4
491     0
492     0
493     4
494     0
495     1
496     1
497     4
498     0
499     0
500     2
501     4
502     4
503     3
504     4
505     1
506     0
507     0
508     0
509     0
510     1
511     4
512     0
513     3
514     2
515     2
516     1
517     0
518     1
519     0
520     4
521     2
522     3
523     1
524     2
525     3
526     4
527     4
528     2
529     3
530     1
531     4
532     0
533     4
534     0
535     0
536     4
537     2
538     4
539     4
540     4
541     0
542     0
543     0
544     0
545     2
546     2
547     4
548     3
549     1
550     4
551     4
552     3
553     1
554     2
555     3
556     0
557     2
558     0
559     0
560     3
561     0
562     0
563     4
564     0
565     4
566     1
567     4
568     2
569     0
570     4
571     3
572     0
573     3
574     1
575     4
576     2
577     0
578     2
579     0
580     0
581     0
582     0
583     0
584     0
585     0
586     3
587     0
588     4
589     4
590     4
591     3
592     4
593     2
594     0
595     0
596     1
597     0
598     3
599     4
600     1
601     0
602     4
603     3
604     2
605     4
606     2
607     3
608     4
609     4
610     0
611     0
612     4
613     3
614     3
615     1
616     0
617     4
618     3
619     0
620     0
621     4
622     2
623     1
624     0
625     1
626     1
627     4
628     4
629     3
630     2
631     3
632     4
633     0
634     2
635     4
636     2
637     4
638     3
639     0
640     4
641     2
642     0
643     3
644     1
645     1
646     0
647     3
648     0
649     1
650     0
651     0
652     2
653     1
654     0
655     0
656     4
657     3
658     0
659     2
660     0
661     0
662     0
663     4
664     3
665     0
666     0
667     3
668     0
669     4
670     3
671     3
672     0
673     1
674     3
675     4
676     3
677     0
678     0
679     3
680     0
681     4
682     0
683     2
684     0
685     0
686     3
687     0
688     3
689     3
690     0
691     2
692     3
693     0
694     1
695     0
696     4
697     0
698     3
699     4
700     4
701     2
702     2
703     0
704     0
705     1
706     4
707     1
708     2
709     2
710     0
711     1
712     4
713     0
714     4
715     3
716     4
717     2
718     1
719     4
720     0
721     4
722     0
723     0
724     2
725     0
726     1
727     0
728     2
729     4
730     3
731     0
732     1
733     4
734     1
735     2
736     2
737     4
738     2
739     4
740     3
741     0
742     0
743     4
744     0
745     4
746     4
747     0
748     3
749     4
750     1
751     4
752     0
753     0
754     0
755     1
756     4
757     0
758     1
759     4
760     0
761     1
762     0
763     4
764     4
765     0
766     1
767     0
768     2
769     1
770     0
771     1
772     0
773     0
774     2
775     4
776     0
777     0
778     4
779     0
780     4
781     0
782     1
783     0
784     4
785     3
786     4
787     2
788     1
789     4
790     4
791     4
792     0
793     2
794     0
795     0
796     2
797     1
798     0
799     4
800     4
801     0
802     2
803     3
804     0
805     4
806     1
807     4
808     2
809     0
810     4
811     4
812     2
813     2
814     0
815     1
816     0
817     3
818     1
819     4
820     4
821     2
822     3
823     0
824     4
825     1
826     0
827     0
828     4
829     2
830     3
831     2
832     4
833     2
834     0
835     4
836     4
837     0
838     2
839     3
840     3
841     4
842     0
843     0
844     0
845     1
846     4
847     0
848     4
849     4
850     4
851     3
852     0
853     0
854     4
855     4
856     4
857     0
858     4
859     4
860     1
861     4
862     1
863     0
864     1
865     0
866     4
867     0
868     4
869     0
870     4
871     3
872     4
873     4
874     3
875     0
876     1
877     3
878     4
879     2
880     0
881     1
882     0
883     4
884     3
885     0
886     0
887     1
888     2
889     4
890     2
891     3
892     2
893     0
894     4
895     2
896     4
897     3
898     0
899     3
900     0
901     0
902     1
903     3
904     4
905     0
906     0
907     1
908     0
909     4
910     0
911     1
912     4
913     0
914     4
915     0
916     1
917     4
918     1
919     1
920     4
921     0
922     1
923     4
924     1
925     2
926     0
927     0
928     4
929     2
930     1
931     2
932     4
933     0
934     0
935     0
936     0
937     0
938     4
939     1
940     1
941     0
942     1
943     4
944     3
945     0
946     0
947     2
948     2
949     2
950     0
951     0
952     1
953     1
954     1
955     0
956     4
957     0
958     1
959     2
960     0
961     1
962     0
963     3
964     0
965     0
966     0
967     0
968     4
969     0
970     0
971     3
972     4
973     3
974     4
975     4
976     0
977     0
978     4
979     2
980     1
981     2
982     2
983     0
984     4
985     2
986     0
987     0
988     1
989     2
990     3
991     4
992     1
993     0
994     0
995     2
996     2
997     0
998     4
999     0
1000    0
1001    1
1002    0
1003    2
1004    1
1005    3
1006    1
1007    0
1008    2
1009    1
1010    0
1011    4
1012    0
1013    0
1014    1
1015    0
1016    4
1017    4
1018    0
1019    1
1020    2
1021    1
1022    0
1023    3
1024    2
1025    4
1026    0
1027    3
1028    1
1029    0
1030    3
1031    1
1032    0
1033    4
1034    4
1035    4
1036    4
1037    0
1038    3
1039    2
1040    0
1041    1
1042    0
1043    2
1044    0
1045    2
1046    3
1047    0
1048    2
1049    0
1050    0
1051    1
1052    2
1053    0
1054    2
1055    2
1056    0
1057    0
1058    0
1059    1
1060    1
1061    4
1062    2
1063    0
1064    0
1065    1
1066    3
1067    1
1068    3
1069    1
1070    0
1071    0
1072    1
1073    0
1074    0
1075    4
1076    4
1077    2
1078    4
1079    0
1080    2
1081    3
1082    0
1083    0
1084    3
1085    0
1086    0
1087    2
1088    1
1089    1
1090    3
1091    2
1092    4
1093    4
1094    2
1095    0
1096    0
1097    1
1098    4
1099    0
1100    1
1101    1
1102    0
1103    3
1104    2
1105    0
1106    4
1107    4
1108    4
1109    2
1110    4
1111    0
1112    4
1113    2
1114    2
1115    2
1116    2
1117    3
1118    3
1119    4
1120    1
1121    3
1122    1
1123    1
1124    0
1125    2
1126    0
1127    1
1128    1
1129    3
1130    1
1131    0
1132    0
1133    0
1134    1
1135    4
1136    4
1137    4
1138    0
1139    0
1140    0
1141    0
1142    0
1143    1
1144    0
1145    2
1146    2
1147    0
1148    0
1149    0
1150    2
1151    0
1152    0
1153    3
1154    3
1155    4
1156    3
1157    4
1158    4
1159    0
1160    1
1161    0
1162    4
1163    0
1164    4
1165    1
1166    0
1167    1
1168    0
1169    4
1170    4
1171    4
1172    2
1173    0
1174    0
1175    0
1176    0
1177    3
1178    1
1179    2
1180    2
1181    1
1182    3
1183    3
1184    1
1185    0
1186    4
1187    4
1188    2
1189    0
1190    2
1191    2
1192    0
1193    3
1194    0
1195    1
1196    4
1197    1
1198    2
1199    1
1200    2
1201    0
1202    3
1203    4
1204    1
1205    0
1206    0
1207    0
1208    0
1209    3
1210    1
1211    0
1212    0
1213    4
1214    1
1215    0
1216    3
1217    4
1218    1
1219    4
1220    1
1221    0
1222    4
1223    0
1224    0
1225    1
1226    4
1227    2
1228    3
1229    4
1230    3
1231    1
1232    2
1233    4
1234    3
1235    4
1236    0
1237    0
1238    1
1239    0
1240    1
1241    2
1242    1
1243    0
1244    1
1245    1
1246    3
1247    1
1248    0
1249    0
1250    3
1251    0
1252    0
1253    0
1254    3
1255    0
1256    4
1257    3
1258    3
1259    3
1260    0
1261    0
1262    0
1263    4
1264    4
1265    3
1266    0
1267    4
1268    4
1269    4
1270    4
1271    3
1272    0
1273    3
1274    4
1275    3
1276    4
1277    4
1278    2
1279    1
1280    4
1281    2
1282    0
1283    4
1284    4
1285    0
1286    0
1287    2
1288    4
1289    4
1290    4
1291    0
1292    4
1293    4
1294    0
1295    4
1296    1
1297    0
1298    1
1299    0
1300    4
1301    4
1302    3
1303    4
1304    1
1305    1
1306    4
1307    2
1308    1
1309    1
1310    2
1311    2
1312    3
1313    3
1314    2
1315    0
1316    0
1317    0
1318    0
1319    0
1320    2
1321    4
1322    0
1323    4
1324    0
1325    0
1326    2
1327    4
1328    1
1329    4
1330    1
1331    0
1332    4
1333    3
1334    0
1335    0
1336    1
1337    2
1338    0
1339    4
1340    0
1341    0
1342    0
1343    4
1344    1
1345    3
1346    0
1347    1
1348    0
1349    3
1350    4
1351    0
1352    4
1353    4
1354    1
1355    0
1356    0
1357    3
1358    0
1359    0
1360    0
1361    0
1362    0
1363    4
1364    3
1365    4
1366    0
1367    4
1368    3
1369    2
1370    1
1371    0
1372    1
1373    0
1374    3
1375    2
1376    0
1377    4
1378    4
1379    4
1380    4
1381    0
1382    3
1383    0
1384    1
1385    3
1386    4
1387    4
1388    0
1389    2
1390    4
1391    2
1392    2
1393    0
1394    4
1395    2
1396    4
1397    0
1398    1
1399    0
1400    0
1401    0
1402    1
1403    0
1404    2
1405    0
1406    4
1407    0
1408    4
1409    2
1410    0
1411    2
1412    1
1413    4
1414    2
1415    4
1416    4
1417    1
1418    4
1419    4
1420    4
1421    0
1422    4
1423    1
1424    3
1425    0
1426    4
1427    3
1428    0
1429    3
1430    1
1431    2
1432    2
1433    0
1434    0
1435    4
1436    0
1437    1
1438    2
1439    0
1440    0
1441    4
1442    3
1443    0
1444    2
1445    1
1446    0
1447    0
1448    1
1449    0
1450    0
1451    1
1452    3
1453    2
1454    2
1455    2
1456    1
1457    2
1458    0
1459    4
1460    0
1461    1
1462    2
1463    0
1464    0
1465    0
1466    0
1467    1
1468    4
1469    2
1470    0
1471    2
1472    0
1473    1
1474    3
1475    4
1476    0
1477    4
1478    2
1479    3
1480    2
1481    4
1482    0
1483    3
1484    4
1485    1
1486    0
1487    3
1488    0
1489    1
1490    4
1491    0
1492    1
1493    0
1494    0
1495    3
1496    0
1497    3
1498    1
1499    4
1500    2
1501    0
1502    3
1503    3
1504    1
1505    0
1506    4
1507    3
1508    1
1509    1
1510    4
1511    4
1512    0
1513    0
1514    4
1515    2
1516    1
1517    3
1518    0
1519    0
1520    0
1521    2
1522    2
1523    0
1524    4
1525    0
1526    0
1527    4
1528    1
1529    4
1530    0
1531    2
1532    0
1533    0
1534    4
1535    0
1536    4
1537    4
1538    0
1539    0
1540    4
1541    4
1542    3
1543    0
1544    2
1545    4
1546    4
1547    4
1548    1
1549    0
1550    0
1551    1
1552    2
1553    2
1554    1
1555    3
1556    0
1557    0
1558    1
1559    0
1560    2
1561    0
1562    0
1563    0
1564    0
1565    3
1566    4
1567    0
1568    0
1569    1
1570    1
1571    0
1572    0
1573    3
1574    1
1575    4
1576    4
1577    1
1578    0
1579    0
1580    1
1581    1
1582    3
1583    0
1584    4
1585    2
1586    4
1587    3
1588    3
1589    0
1590    4
1591    1
1592    2
1593    0
1594    4
1595    0
1596    0
1597    3
1598    1
1599    4
1600    0
1601    3
1602    2
1603    1
1604    4
1605    4
1606    4
1607    0
1608    1
1609    3
1610    3
1611    4
1612    4
1613    2
1614    4
1615    3
1616    3
1617    1
1618    1
1619    4
1620    0
1621    2
1622    3
1623    3
1624    3
1625    0
1626    1
1627    0
1628    2
1629    4
1630    2
1631    1
1632    3
1633    0
1634    4
1635    0
1636    3
1637    4
1638    4
1639    1
1640    0
1641    4
1642    2
1643    2
1644    2
1645    2
1646    4
1647    0
1648    4
1649    1
1650    0
1651    0
1652    1
1653    4
1654    0
1655    0
1656    3
1657    2
1658    3
1659    4
1660    3
1661    4
1662    0
1663    3
1664    3
1665    0
1666    0
1667    0
1668    3
1669    0
1670    0
1671    4
1672    4
1673    2
1674    1
1675    2
1676    0
1677    0
1678    4
1679    0
1680    3
1681    4
1682    4
1683    1
1684    2
1685    1
1686    1
1687    0
1688    2
1689    0
1690    4
1691    4
1692    2
1693    4
1694    0
1695    3
1696    0
1697    4
1698    4
1699    2
1700    3
1701    4
1702    1
1703    0
1704    0
1705    3
1706    4
1707    0
1708    0
1709    2
1710    0
1711    4
1712    2
1713    3
1714    4
1715    3
1716    0
1717    4
1718    1
1719    0
1720    0
1721    0
1722    3
1723    0
1724    0
1725    1
1726    2
1727    2
1728    3
1729    4
1730    0
1731    0
1732    4
1733    0
1734    0
1735    4
1736    0
1737    0
1738    4
1739    0
1740    2
1741    1
1742    0
1743    4
1744    2
1745    3
1746    4
1747    0
1748    3
1749    3
1750    3
1751    0
1752    1
1753    4
1754    4
1755    0
1756    3
1757    3
1758    4
1759    1
1760    3
1761    4
1762    2
1763    0
1764    4
1765    4
1766    1
1767    4
1768    4
1769    4
1770    2
1771    0
1772    0
1773    4
1774    0
1775    4
1776    4
1777    1
1778    4
1779    0
1780    1
1781    4
1782    1
1783    0
1784    0
1785    4
1786    2
1787    2
1788    3
1789    3
1790    0
1791    3
1792    2
1793    4
1794    4
1795    1
1796    1
1797    2
1798    2
1799    0
1800    0
1801    1
1802    0
1803    2
1804    2
1805    4
1806    2
1807    0
1808    1
1809    2
1810    4
1811    1
1812    1
1813    0
1814    0
1815    4
1816    0
1817    4
1818    4
1819    4
1820    0
1821    2
1822    2
1823    1
1824    4
1825    2
1826    4
1827    3
1828    2
1829    0
1830    2
1831    1
1832    3
1833    0
1834    0
1835    0
1836    1
1837    0
1838    3
1839    0
1840    4
1841    3
1842    3
1843    4
1844    4
1845    4
1846    1
1847    3
1848    2
1849    0
1850    3
1851    0
1852    0
1853    0
1854    0
1855    3
1856    2
1857    4
1858    1
1859    3
1860    4
1861    0
1862    3
1863    0
1864    1
1865    3
1866    4
1867    0
1868    0
1869    4
1870    0
1871    3
1872    2
1873    4
1874    2
1875    4
1876    3
1877    4
1878    0
1879    0
1880    0
1881    1
1882    2
1883    2
1884    1
1885    1
1886    4
1887    1
1888    1
1889    0
1890    0
1891    0
1892    0
1893    1
1894    3
1895    4
1896    2
1897    2
1898    0
1899    1
1900    0
1901    0
1902    4
1903    0
1904    3
1905    2
1906    2
1907    0
1908    4
1909    0
1910    0
1911    4
1912    3
1913    4
1914    0
1915    1
1916    3
1917    4
1918    1
1919    0
1920    1
1921    4
1922    1
1923    2
1924    1
1925    4
1926    3
1927    3
1928    2
1929    0
1930    0
1931    3
1932    0
1933    1
1934    0
1935    3
1936    3
1937    0
1938    0
1939    0
1940    4
1941    0
1942    3
1943    0
1944    0
1945    4
1946    3
1947    4
1948    0
1949    4
1950    4
1951    0
1952    1
1953    0
1954    0
1955    3
1956    4
1957    3
1958    1
1959    0
1960    2
1961    2
1962    1
1963    0
1964    4
1965    1
1966    1
1967    4
1968    3
1969    4
1970    0
1971    1
1972    1
1973    4
1974    0
1975    1
1976    0
1977    2
1978    3
1979    3
1980    0
1981    4
1982    0
1983    1
1984    0
1985    0
1986    4
1987    1
1988    4
1989    2
1990    1
1991    3
1992    1
1993    0
1994    1
1995    0
1996    4
1997    4
1998    0
1999    1

In [73]:
df['tenure_group'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   category
dtypes: category(1)
memory usage: 7.2 KB

In [74]:
df['tenure_group'] = df['tenure_group'].astype(float).astype(int)
df['tenure_group'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   int32
dtypes: int32(1)
memory usage: 27.6 KB

In [75]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,2
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0

In [76]:
df['avg_monthly_per_tenure'] = df['TotalCharges'] / (df['tenure'] + 1)

In [77]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'tenure_group', 'avg_monthly_per_tenure'],
      dtype='object')

### Encoding

In [78]:
df = df.drop('customerID', axis = 1)

In [79]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,14.925000
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,2,53.985714
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,36.050000
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,3,40.016304
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,50.550000

In [80]:
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0})
    
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,Female,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,No,0,14.925000
1,Male,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,No,2,53.985714
2,Male,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,Yes,0,36.050000
3,Male,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,No,3,40.016304
4,Female,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,Yes,0,50.550000

In [81]:
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

In [82]:
df['gender'] = df['gender'].map({'Male':1,'Female':0})

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  7043 non-null   int64
 1   SeniorCitizen           7043 non-null   int64
 2   Partner                 7043 non-null   int64
 3   Dependents              7043 non-null   int64
 4   tenure                  7043 non-null   int64
 5   PhoneService            7043 non-null   int64
 6   MultipleLines           7043 non-null   object
 7   InternetService         7043 non-null   object
 8   OnlineSecurity          7043 non-null   object
 9   OnlineBackup            7043 non-null   object
 10  DeviceProtection        7043 non-null   object
 11  TechSupport             7043 non-null   object
 12  StreamingTV             7043 non-null   object
 13  StreamingMovies         7043 non-null   object
 14  Contract                7043 non-null   object
 15  PaperlessBilling        7043 non-null   int64
 16  PaymentMethod           7043 non-null   object
 17  MonthlyCharges          7043 non-null   float64
 18  TotalCharges            7043 non-null   float64
 19  Churn                   7043 non-null   int64
 20  tenure_group            7043 non-null   int32
 21  avg_monthly_per_tenure  7043 non-null   float64
dtypes: float64(3), int32(1), int64(8), object(10)
memory usage: 1.2+ MB

In [84]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
categorical_cols

['MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaymentMethod']

In [85]:
for col in categorical_cols:
    le = LabelEncoder()
    
    df[col] = le.fit_transform(df[col].astype(str))

In [86]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0,0,14.925000
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0,2,53.985714
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1,0,36.050000
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0,3,40.016304
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1,0,50.550000